### ISSUE TITLE
Update docs for Redis

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#183]
## Description

Update the `.env.example` file and our docs with Redis configuration. 

## Solution

Here are the configurations that you will be adding to the docs:

- `REDIS_URL`: This is the URL that is used to connect to Redis instance. The url is used by the `api`. It is a required parameter
- `REDIS_PASSWORD`: Optional parameter. Specified only if the Redis instance is configured to use a password. Used by the `api`

**Changes required**
- Update the `.env.example` file to contain both the keys. Additionally, you will need to add a default value of `redis://localhost:6379` to `REDIS_URL`.
- Update the [Environmental Variables](https://github.com/keyshade-xyz/keyshade/blob/develop/docs/contributing-to-keyshade/environment-variables.md) file. This will be containing detailed info about both the variables.

**Comment by qhtutorials** [comment]
Hi, I’m a beginner and I’d like to help. I will add the REDIS_URL and REDIS_PASSWORD details to the environment-variables.md file.

I just had one question. Because the .env.example file contains “REDIS_URL=redis://127.0.0.1:6739” and “REDIS_PASSWORD=”, it already has both keys and the default value? Or should I change the default value to redis://localhost:6739?

**Comment by rajdip-b** [comment]
Hey @qhtutorials, I think you can leave the values as is! We had some rapid development and some of the issues got outdated without our notice. It's good that you pointed this out. Rest assured, your PR will be considered valid just if it fills the missing pieces! 

Do hop on to our Discord channel if you want to dig deeper!
