### ISSUE TITLE
API : Improvement required in Fetching all forks of Project.

### ISSUE THREAD

**Issue by muntaxir4** [keyshade-xyz/keyshade#369]
https://github.com/keyshade-xyz/keyshade/blob/eb271d47c787db4ab90ba1a38c41f48de7897125/apps/api/src/project/service/project.service.ts#L577C1-L609C4

The logic used here is to slice the `forks` into required page and limit first, then checked for authority.

**Known issue:** During final return there could be cases where within those sliced content the allowed items were less, thus contradicting required result.

**Solution:** Check the authority before then slice it to required page and limit.

**Comment by muntaxir4** [comment]
Assign me this if you find the issue is valid.

**Comment by rajdip-b** [comment]
I think this is a valid issue, but I'm not entirely sure how we should approach this. We certainly won't want to query all the forks on to the ram since that will not be a good thing.

Maybe we can do this: 
- Query pageSize*2 items
- Filter through all of them to check the authority
- After filtering, if size < page, we again query the db, this time increasing the starting index by pageSize.
- After filtering, if size>page, we simply disregard the last few elements.

**Comment by muntaxir4** [comment]
@rajdip-b I have linked #393 to this. As pagination would require totalCount of projects user is authorized, I have went on to checking authority for all fetched ones :).

**Comment by rajdip-b** [comment]
The solution looks good!
