### ISSUE TITLE
API: Remove `projectIds` from `Export Workspace Data` response.

### ISSUE THREAD

**Issue by rajdip-b** [keyshade-xyz/keyshade#425]
## Description
![image](https://github.com/user-attachments/assets/948fd987-c3bd-4ce9-a17c-56f7dda755b0)

Calling `/api/workspace/:workspaceSlug/export-data` fetches us all the roles, projects, environments, variables and secrets of a workspace. Just that in the roles listing, we also get the `projectIds` associated to that role. We would want to exclude this selection.

## Solution
- Changes needs to be done to this function: https://github.com/keyshade-xyz/keyshade/blob/a97681edab4ffb670b4479e3a8d2d2879c75f992/apps/api/src/workspace/service/workspace.service.ts#L275-L356
- Update the E2E tests in `workspace.e2e.spec.ts` to reflect this scenario.

**Comment by Meeran-Tofiq** [comment]
Hello, everyone!

In the issue it is stated that there are changes that need to be made to the E2E tests of `workspace.e2e.spec.ts`, however upon inspection, the tests do not contain anything that checks for project IDs being exported. Meaning that despite me removing them, all the tests in the API ran successfully. 

If it is necessary for me to make new tests to make sure that there ISN'T project IDs in the exported data, I'd gladly do so. But I didn't want to fill the test file with unnecessary tests, unless instructed to otherwise.

Should I implement the new tests?

**Comment by rajdip-b** [comment]
I think in that case you can update the existing test to do a deep equality check for the presence of the fields (not the values). That should do it.

**Comment by Meeran-Tofiq** [comment]
![Screenshot from 2024-09-15 14-38-32](https://github.com/user-attachments/assets/effae968-20a0-4e34-ad82-537f3dce0100)

Hello again. I believe this test already adequately tests for the existence of necessary keys in the returned object. I believe it will be unnecessary to make changes to it. 

I am a beginner and I apologize if I'm going about this the wrong way.

If no extra tests are required, I will go ahead and make the pull request :)

**Comment by rajdip-b** [comment]
Hey! We do appreciate you pinging us with your suggestion. In fact, we encourage that highly.

Coming to your question, yes, this is present. What we also want is, just try to fetch the 0th element in the array and check if the required fields are present or not. That's all that we need.
